stages: 
- test
- deploy 

# testing stage
test:
  # defining the stage name
  stage: test

  # defining the base image 
  image: hub.hamdocker.ir/library/python:3.9-slim-buster

  # defining the services which it depends on
  services:
    - name: hub.hamdocker.ir/library/postgres:13-alpine
      alias: db

  # scripts which needs to be run before main script
  before_script:
    - pip3 install -r requirements.txt
    - cd ./core
    - export DJANGO_SETTINGS_MODULE=core.settings

  # main script for testing django app
  script:
    - python manage.py makemigrations
    - python manage.py migrate
    - pytest .

  # variables for service and main image
  variables:
    DATABASE: postgres
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    DB_VENDOR: postgres
    PGDATA: /var/lib/postgresql/data


# deployment stage
deploy:
  stage: deploy
  script: curl --location --request GET 'https://api.console.hamravesh.ir/api/v1/darkube/build/build_last_commit/?app_id=$HAMRAVESH_APP_ID' \
          --header 'x-organization: $HAMRAVESH_ORG_NAME' \
          --header 'Authorization: Api-key $HAMRAVESH_API_KEY'
