# migration docs: https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-gitlab-cicd-to-github-actions
name: Django Project Test and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# defining all jobs
jobs:
  # testing job
  Test:
    # defining the job name
    name: Test


    # which operating system its going to use
    runs-on: ubuntu-latest

    # defining the base image
    container:
      image: docker.io/python:3.9-slim-buster

    # defining the services which it depends on
    services:
      db:
        image: docker.io/postgres:alpine

    # scripts which needs to be run before main script
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies and migrate database
        run: |
          pip3 install -r requirements.txt
          cd ./core
          python manage.py migrate
          python manage.py check
      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: core.settings
        run: pytest .

    # variables for service and main image
    env:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # building job
  darkube_build:
    # name of the job
    name: Build

     # which operating system its going to use
    runs-on: ubuntu-latest

    # using darkube image cli
    container:
      image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1

    # only doing the job in prod mode
    if: startsWith(github.ref, 'refs/heads/stage')

    # defining specific runners
    # runs-on:
    #   - my-runner

    # running build script for the project
    # name of the predefined env variables: https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build --push -t ${{ secrets.DOCKER_REGISTRY }}/image-name:${{ github.sha }} -t ${{ secrets.DOCKER_REGISTRY }}/image-name:${{ github.ref_slug }} --file ./dockerfiles/prod/django/Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg CACHE_TAG=${{ github.sha }} .

  # deployment job
  darkube_deploy:
    # name of the job
    name: Deploy

     # which operating system its going to use
    runs-on: ubuntu-latest
    
    # using darkube image cli
    container:
      image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1


    # running deploy script for the project
    # name of the predefined env variables: https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Darkube
        env:
          DARKUBE_APP_ID: ${{ secrets.DARKUBE_APP_ID }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF_SLUG: ${{ github.ref_slug }}
        run: darkube deploy --ref prod --token ${{ secrets.GITHUB_TOKEN }} --app-id $DARKUBE_APP_ID --image-tag "${GITHUB_SHA}" --job-id "${{ github.job }}" --stateless-app true
