
name: Django Project Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres: 
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432 # exposing 5432 port for application to use
    steps:
    - uses: actions/checkout@v3
    - name: unpack environments
      run: cp ./envs/dev/django/.env.sample ./envs/dev/django/.env
    - name: Setup docker image
      run: docker build -t test-app  -f ./dockerfiles/dev/django/Dockerfile .
    - name: Run Tests
      run: docker run test-app sh -c "yes | python manage.py makemigrations  && yes | python manage.py migrate && python manage.py test"

  
  # Deploy:
  #   if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} 
  #   name: Deploy
  #   needs: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Connect and Execute Commands
  #     uses: appleboy/ssh-action@master
  #     with:
  #       username: ${{secrets.USERNAME}}
  #       password: ${{secrets.PASSWORD}}
  #       host: ${{secrets.HOST}}
  #       port: ${{secrets.PORT}}
  #       script: |
  #         cd ${{secrets.PROJECT_PATH}}
  #         docker compose -f docker-compose-prod.yml stop
  #         git pull
  #         docker compose -f docker-compose-prod.yml restart
          