name: Django Project Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: unpack environments
      run: cp ./envs/dev/django/.env.sample ./envs/dev/django/.env && cp ./envs/dev/postgre/.env.sample ./envs/dev/postgre/.env
    - name: Setup Docker-Compose
      run: docker-compose up -d
    - name: Run Tests
      run: docker-compose exec -T backend sh -c "python manage.py test"

  Deploy:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} 
    name: Deploy
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy to hamravesh
      run: |
        curl --location --request GET 'https://api.console.hamravesh.ir/api/v1/darkube/build/build_last_commit/?app_id=a2d4014a-7742-44e0-a386-39a68d32f52f' \
        --header 'x-organization: sama' \
        --header 'Authorization: Api-key 76d9d830-70b8-4efc-b88e-10ce0b4c5c22'
